services:

  feature_pipeline:
    build: .
    container_name: asteroid-feature-pipeline
    env_file: .env.local
    command: python -m src.feature_pipeline.pipeline --mode incremental

  feature_pipeline_weekly:
    build: .
    container_name: asteroid-feature-pipeline-weekly
    env_file: .env.local
    command: python -m src.feature_pipeline.pipeline --mode weekly

  feature_pipeline_backfill:
    build: .
    container_name: asteroid-feature-pipeline-backfill
    env_file: .env.local
    command: python -m src.feature_pipeline.pipeline --mode backfill --max-pages 1000 --start-page 0

  training_pipeline:
    build: .
    container_name: asteroid-training-pipeline
    env_file: .env.local
    command: python -m src.training_pipeline.pipeline

  inference_pipeline:
    build: .
    container_name: asteroid-inference-pipeline
    env_file: .env.local
    command: python -m src.inference_pipeline.pipeline

  ui:
    build: .
    container_name: asteroid-ui
    env_file: .env.local
    command: python -m src.ui.app
    ports:
      - "7860:7860"
    restart: unless-stopped

  monitoring_pipeline:
    build: .
    container_name: asteroid-monitoring-pipeline
    env_file: .env.local
    command: python -m src.monitoring_pipeline.pipeline

  tests:
    build: .
    container_name: asteroid-tests
    env_file: .env.local
    volumes:
      - ./tests:/app/tests
    command: python -m pytest tests/ -v