services:

  feature_pipeline:
    build: .
    container_name: asteroid-feature-pipeline
    env_file: .env.local
    command: python -m src.feature_pipeline.pipeline --mode incremental

  feature_pipeline_weekly:
    build: .
    container_name: asteroid-feature-pipeline-weekly
    env_file: .env.local
    command: python -m src.feature_pipeline.pipeline --mode weekly

  feature_pipeline_backfill:
    build: .
    container_name: asteroid-feature-pipeline-backfill
    env_file: .env.local
    command: python -m src.feature_pipeline.pipeline --mode backfill --max-pages 1000 --start-page 200

  training_pipeline:
    build: .
    container_name: asteroid-training-pipeline
    env_file: .env.local
    command: python -m src.training_pipeline.pipeline

  inference_pipeline:
    build: .
    container_name: asteroid-inference-pipeline
    env_file: .env.local
    command: python -m src.feature_pipeline.pipeline

